project:
  type: website
  output-dir: docs

website:
  title: "cyo-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - reading.qmd
      - resume.qmd

format:
  html:
    theme:
      - quartz
      - brand
    css: styles.css
    toc: true

editor: visual

