project:
  type: website
  output-dir: docs

website:
  title: "Valeria Fierros"
  favicon: Logo maker project.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - reading.qmd
      - resume.qmd

format:
  html:
    theme:
      - sketchy
      - styles.scss 
    toc: true

editor: visual

