project:
  type: website
  output-dir: docs

website:
  title: "Valeria Fierros"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - reading.qmd
      - resume.qmd

format:
  html:
    theme:
      light: quartz
      dark: vapor
    css: styles.css
    toc: true

editor: visual

